- name: Copying file from local to remote
  hosts: "{{hosts}}"
  tasks:
     - name: Restoring Files
       win_copy:
        src: "{{src_path}}{{ ansible_host }}/{{drive}}:/"
        dest: "{{drive}}:/"
